// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCC6JdVTsoTG9J0Gm5XEsuXgvz0zeezGVQ',
    appId: '1:52970712912:web:bfe71f3454f7de0a9dc655',
    messagingSenderId: '52970712912',
    projectId: 'ecommerce-b786e',
    authDomain: 'ecommerce-b786e.firebaseapp.com',
    storageBucket: 'ecommerce-b786e.firebasestorage.app',
    measurementId: 'G-KR1RP0XKTV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCMIQg3_v0dCw-8Hbi6y2HbdvoVEOLp-jI',
    appId: '1:52970712912:android:a965599afa00639c9dc655',
    messagingSenderId: '52970712912',
    projectId: 'ecommerce-b786e',
    storageBucket: 'ecommerce-b786e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB3Eojzz8hwbSx2eah3lfWgGTFpV9E5_Yw',
    appId: '1:52970712912:ios:33f0ac36d02d13be9dc655',
    messagingSenderId: '52970712912',
    projectId: 'ecommerce-b786e',
    storageBucket: 'ecommerce-b786e.firebasestorage.app',
    iosBundleId: 'com.example.eCommerce',
  );
}
